# Generated by Django 2.2 on 2019-04-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atkd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='atkd.Parents')),
            ],
        ),
    ]
