# Generated by Django 2.2 on 2019-04-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atkd', '0002_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parents',
            new_name='parent',
        ),
    ]
